FROM python:3.8-buster

WORKDIR /app

COPY ./requirements.txt ./requirements.txt
RUN pip3 install -r requirements.txt

COPY ./sync ./sync
COPY ./db ./db
COPY ./main_sync.py ./main_sync.py

CMD [ "python3", "main_sync.py" ]